#! /usr/bin/env php
<?php

/**
 * Wordpress Installer
 * @author Samet Aydemir <sametaydemir@yandex.com>
 */

require __DIR__ . '/vendor/autoload.php';

use wpup\wpup;
use Symfony\Component\Console\Application;

$wpup = new Application('Wordpress Installer', '1.0');

$wpup->add(new wpup(new GuzzleHttp\Client()));

$wpup->run();
